# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 11:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='static/avatars/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('status', models.CharField(choices=[('D', 'Divorced'), ('S', 'Single'), ('O', 'Others')], max_length=1)),
                ('religion', models.BooleanField(default=True, verbose_name='Shomer Shabbat')),
                ('children', models.BooleanField(default=False, verbose_name='Children')),
                ('descrption', models.TextField(blank=True, default='', verbose_name='Title Description')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tonight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('flyer', models.ImageField(blank=True, null=True, upload_to='static/fliyers/')),
                ('comment', models.TextField(blank=True, default='')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('event_date', models.DateField(verbose_name='Date Event')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country')),
            ],
        ),
    ]
