# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rencontre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonight',
            name='event_date',
            field=models.DateField(default='', verbose_name='Date Event'),
        ),
    ]
