# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('rencontre', '0003_auto_20160331_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='search_city',
            field=models.ForeignKey(default=396, on_delete=django.db.models.deletion.CASCADE, related_name='search_city', to='cities_light.City'),
            preserve_default=False,
        ),
    ]
